package com.joe.smt.entity;

// Generated Jun 21, 2016 3:17:11 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Authorities generated by hbm2java
 */
@Entity
@Table(name = "authorities", catalog = "springmvctest", uniqueConstraints = @UniqueConstraint(columnNames = { "username", "authority" }))
public class Authorities implements java.io.Serializable {

	private AuthoritiesId id;
	private Users users;

	public Authorities() {
	}

	public Authorities(AuthoritiesId id, Users users) {
		this.id = id;
		this.users = users;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "username", column = @Column(name = "username", nullable = false)),
			@AttributeOverride(name = "authority", column = @Column(name = "authority", nullable = false)) })
	public AuthoritiesId getId() {
		return this.id;
	}

	public void setId(AuthoritiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
